import {
  Droplets,
  Wrench,
  Flame,
  ShowerHead,
  Waves,
  ArrowDownToLine,
  RefreshCw,
  GlassWater,
  FilterX,
  Snowflake,
  Thermometer,
  Gauge,
  Wind,
  Fan,
  AirVent,
  Building2,
  Zap,
  PlugZap,
  BatteryCharging,
  ShieldAlert,
  Cable,
  Lightbulb,
  CircuitBoard,
  Shovel,
  Route,
  type LucideIcon
} from 'lucide-react';
import type { Service } from '../data/services';

/** Shared icon lookup for Service['icon'], reused wherever a service card
 * needs to resolve its icon name to a component. */
export const serviceIconMap: Record<Service['icon'], LucideIcon> = {
  Droplets,
  Wrench,
  Flame,
  ShowerHead,
  Waves,
  ArrowDownToLine,
  RefreshCw,
  GlassWater,
  FilterX,
  Snowflake,
  Thermometer,
  Gauge,
  Wind,
  Fan,
  AirVent,
  Building2,
  Zap,
  PlugZap,
  BatteryCharging,
  ShieldAlert,
  Cable,
  Lightbulb,
  CircuitBoard,
  Shovel,
  Route
};
